import { NextRequest, NextResponse } from 'next/server';

export async function POST(req: NextRequest) {
  try {
    const { code, format, title } = await req.json();

    if (!code) {
      return NextResponse.json({ error: 'No code provided' }, { status: 400 });
    }

    const safeTitle = (title || 'MT_VBA_Tool').replace(/[^a-z0-9]/gi, '_').toLowerCase();
    
    if (format === 'mac') {
      const escapedCode = code.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
      const script = `#!/bin/bash
# MT Automated VBA Setup for Mac
# Code: ${title || 'Generated VBA'}

osascript <<EOD
tell application "Microsoft Excel"
    activate
    make new workbook
    set newWorkbook to active workbook
    set value of cell "A1" of sheet 1 of newWorkbook to "MT AI VBA CODE GENERATED:"
    set value of cell "A2" of sheet 1 of newWorkbook to "${escapedCode}"
    display alert "Excel is ready! 

1. Press Option + F11 to open the Editor.
2. Go to Insert > Module.
3. Your code is in Sheet1 A2 - just copy and paste it!

This is the fastest automated setup for Mac."
end tell
EOD
`;
      return new NextResponse(script, {
        headers: {
          'Content-Type': 'application/x-sh',
          'Content-Disposition': `attachment; filename="${safeTitle}_mac_setup.command"`,
        },
      });
    }

    if (format === 'windows') {
      const escapedCode = code.replace(/"/g, '""').replace(/\n/g, '" & vbCrLf & "');
      const script = `Set objExcel = CreateObject("Excel.Application")
objExcel.Visible = True
Set objWorkbook = objExcel.Workbooks.Add()
Set objSheet = objWorkbook.Sheets(1)

objSheet.Cells(1, 1).Value = "MT AI VBA CODE GENERATED:"
objSheet.Cells(2, 1).Value = "${escapedCode}"

MsgBox "Excel is ready!" & vbCrLf & vbCrLf & _
       "1. Press Alt + F11 to open the Editor." & vbCrLf & _
       "2. Go to Insert > Module." & vbCrLf & _
       "3. Your code is in Sheet1 A2 - just copy and paste it!" & vbCrLf & vbCrLf & _
       "This is the fastest automated setup for Windows.", vbInformation, "MT VBA Automated Setup"
`;
      return new NextResponse(script, {
        headers: {
          'Content-Type': 'text/vbs',
          'Content-Disposition': `attachment; filename="${safeTitle}_win_setup.vbs"`,
        },
      });
    }

    if (format === 'notebook') {
      const notebook = `-----------------------------------------
MT ULTRA TOOLS - AI VBA NOTEBOOK
-----------------------------------------
TITLE: ${title || 'Excel Automation Script'}
DATE: ${new Date().toLocaleString()}
-----------------------------------------

USER REQUEST:
(Refer to chat history)

GENERATED VBA CODE:
=========================================
${code}
=========================================

INSTRUCTIONS:
1. Open Excel and press Alt + F11 (Windows) or Option + F11 (Mac).
2. Go to Insert > Module.
3. Paste the code above.
4. Run your macro!

-----------------------------------------
Generated by MT Ultra Assistant
`;
      return new NextResponse(notebook, {
        headers: {
          'Content-Type': 'text/plain',
          'Content-Disposition': `attachment; filename="${safeTitle}_notebook.txt"`,
        },
      });
    }

    return NextResponse.json({ error: 'Invalid format' }, { status: 400 });

  } catch (error) {
    console.error('Download error:', error);
    return NextResponse.json({ error: 'Failed to generate file' }, { status: 500 });
  }
}
